// app/components/SiteNav.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router';
import { PatreonLink } from './PatreonLink';
import { NewBadge } from './NewBadge';
import { useQuery } from '@tanstack/react-query';
import { getBadges } from '~/services/comicsService';

export function SiteNav() {
  const [isCharactersBadgeEnabled, setIsCharactersBadgeEnabled] = useState(false);

  const { data } = useQuery({
    queryKey: ['characters-badge'],
    queryFn: getBadges,
  });

  useEffect(() => {
    if (data?.newCharacters === true) {
      setIsCharactersBadgeEnabled(true);
    }
  }, [data]);

  return (
    <nav id="top" className="my-2 flex w-full flex-col items-center justify-between px-4 lg:flex-row">
      <PatreonLink />
      <div className="text-size-md text-primary mt-4 flex flex-wrap justify-center gap-2 font-bold lg:mt-0">
        <Link className="hover:text-white" to="/">
          Comic
        </Link>
        <span className="text-gray-600">|</span>
        <Link className="hover:text-white" to="/rileycomic">
          Riley Comic
        </Link>
        <span className="text-gray-600">|</span>
        <Link className="group relative hover:text-white" to="/characters">
          Characters
          {isCharactersBadgeEnabled && <NewBadge />}
        </Link>
        <span className="text-gray-600">|</span>
        <Link className="hover:text-white" to="/sketches">
          Sketches
        </Link>
        <span className="text-gray-600">|</span>
        <Link className="group relative hover:text-white" to="/links">
          Links
        </Link>
      </div>
    </nav>
  );
}

// src/components/SiteNav.vue
<template>
  <nav
      class="
      flex flex-col
      justify-between
      items-center
      w-full
      my-2
      px-4
      lg:flex-row
    "
  >
    <patreon-link></patreon-link>
    <div class="mt-4 lg:mt-0 text-center text-size-md text-primary font-bold">
      <router-link class="hover:text-white" to="/">Comic</router-link>
      <span class="px-2 text-gray-600">|</span>
      <router-link class="hover:text-white" to="/rileycomic">Riley Comic</router-link>
      <span class="px-2 text-gray-600">|</span>
      <router-link class="hover:text-white relative group" to="/characters">
        Characters
        <new-badge v-if="isCharactersBadgeEnabled"></new-badge>
      </router-link>
      <span class="px-2 text-gray-600">|</span>
      <router-link class="hover:text-white" to="/sketches">Sketches</router-link>
      <span class="px-2 text-gray-600">|</span>
      <router-link class="hover:text-white relative group" to="/links">
        Links
      </router-link>
    </div>
  </nav>
</template>

<script>
import PatreonLink from '@/components/PatreonLink.vue'
import {mapActions, mapGetters} from 'vuex'
import NewBadge from '@/components/NewBadge.vue'

export default {
  name: 'SiteNav',
  components: {
    NewBadge,
    PatreonLink,
  },
  computed: {
    ...mapGetters({
      isLoreBadgeEnabled: 'isLoreBadgeEnabled',
      isCharactersBadgeEnabled: 'isCharactersBadgeEnabled'
    }),
  },
  methods: {
    ...mapActions(['loadBadges']),
  },
  mounted() {
    this.loadBadges()
  },
}
</script>

<style scoped></style>
